[23기 송진수] Add: 상품 정렬,필터링 API
wecode-bootcamp-korea/23-1st-Gaebalance-backend pull request #12
Opened 2021-08-09 08:52 UTC by jssong1592

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 상품 리스트 필터링/정렬 API
		 
## 수정 사항들 자세한 내용
아래 5가지 종류의 쿼리 객체를 만들어 필터링을 적용하였습니다. 
- group : 남성/여성
- sub_category : 옷 종류 id (다중 선택 가능)
- color : 색상 id (다중 선택 가능)
- size : 사이즈 id (해당 사이즈의 상품이 DB에 존재할 경우 O) 
- price : 가격대 (다중 선택 가능)

필터링 적용 이후 정렬 기준에 해당하는 문자열을 받아 쿼리셋을 정렬(default='id')하고, 필요한 데이터를 Json 형태로 응답합니다.

![image](https://user-images.githubusercontent.com/84955774/128679439-88c5f552-8655-44eb-8fa5-410fb261bb7c.png)

## 기타 질문 및 특이 사항
size의 경우 모델링 구조상 products 테이블이 아니라, products_options 테이블에서 size_id를 찾고, 그 size_id를 가진 데이터의 product_id를 참조해야 합니다.

이런 이중 쿼리를 Q 객체로 어떻게 다뤄야할지 잘 감이 안 잡혀 결국 values() 메서드를 쓸 수 밖에 없었습니다.. 
이보다 확실하고 더 좋은 방법이 있을지 궁금합니다! 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-10 02:04 UTC, Kang-kyunghun requested changes

2021-08-10 02:04 UTC, Kang-kyunghun commented on gaebalance/urls.py
> +
공백 제거해 주세요.

2021-08-10 02:04 UTC, Kang-kyunghun commented on products/views.py
> +class ProductListView(View):
```suggestion
class ProductsView(View):
```

2021-08-10 02:04 UTC, Kang-kyunghun commented on products/views.py
> +        size_filter         = Q()
Q을 활용하신 점 잘 하셨습니다. 
제가 조금 조언을 드리자면, 보통 Q을 사용할 때는 빈 Q을 1번만 선언하고 선언한 Q에 계속 조건을 쌓아가는 형식을 많이 사용합니다.
```suggestion
       q = Q()
       
        if group:
            if group == 'men':
                q &= Q(group='남자')
            else:
                q &= Q(group='여자')
```

2021-08-10 02:04 UTC, Kang-kyunghun commented on products/views.py
> +                group_filter = Q(group='여자')
애초에 받는 값을 '남자' 또는 '여자'로 받으면 if / else을 안 사용해도 될 것 같습니다. 어떻게 생각하세요?

2021-08-10 02:04 UTC, Kang-kyunghun commented on products/views.py
> +                sub_category_filter |= Q(sub_category=sub_category)
django filtering 할 때 __in 을 사용하면 list을 적용할 수 있습니다. 한 번 찾아보고 적용해 보세요.

2021-08-10 02:04 UTC, Kang-kyunghun commented on products/views.py
> +                price_range_filter |= Q(price__gte=200000)
가격 부분은 따로 이야기 할게요.

2021-08-10 02:26 UTC, jssong1592 commented on products/views.py
> +class ProductListView(View):
뷰 이름 제안해주신 대로 수정하겠습니다!

2021-08-10 02:29 UTC, jssong1592 commented on products/views.py
> +                group_filter = Q(group='여자')
넵 한글 문자열을 직접 받을 수 있는게 편리할 것 같습니다. URI에 쿼리 붙이는 내용을 변경해달라고 프론트와 상의해보겠습니다!

2021-08-10 02:31 UTC, jssong1592 commented on products/views.py
> +        size_filter         = Q()
Q 객체 하나로 필터 쿼리를 쌓을 수 있도록 코드를 수정해보겠습니다

2021-08-10 12:24 UTC, jssong1592 commented on gaebalance/urls.py
> +
지금까지 main branch에 반영된 사항을 pull 하여 현재 브랜치에 merge했습니다!

2021-08-10 12:30 UTC, jssong1592 commented on products/views.py
> +                sub_category_filter |= Q(sub_category=sub_category)
__in을 사용하여 리스트를 받을 수 있도록 적용했습니다!

2021-08-10 12:37 UTC, jssong1592 commented on products/views.py
> +                price_range_filter |= Q(price__gte=200000)
경훈님...ㅜㅜ json.loads 사용해서 리스트 형태로 데이터 받을 수 있는 법 알려주셔서 감사합니다! 그런데 가영님한테 이중 배열을 쿼리 변수로 붙여 호출해줄 수 있는지 얘기해보니, 너무 어려울 것 같다고 하셨습니다.. 고민 끝에 가영님과 우선 데이터를 주고 받을 수 있는 방법으로 딕셔너리로 1:1 대응시키는 방식으로 수정하여 올립니다.

2021-08-11 05:53 UTC, jssong1592 commented
오후 코드 리뷰 주신 대로 중복되는 코드를 정리하고, 가격 구간 필터에서도 키에러 핸들링이 될 수 있게끔 get 함수를 추가했습니다.

감사합니다!

![image](https://user-images.githubusercontent.com/84955774/128976382-beab1a49-f6a8-46f5-be1f-f9b9fa4595cd.png)

2021-08-11 10:23 UTC, Kang-kyunghun commented
고생 많으셨습니다~~~ LGTM~~!!

2021-08-11 10:23 UTC, merged