Add : 제품 상세 정보 호출 API
wecode-bootcamp-korea/23-1st-Gaebalance-backend pull request #4
Opened 2021-08-05 07:00 UTC by jssong1592

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 제품 상세 정보 호출 API 추가
		 
## 수정 사항들 자세한 내용
- 상품 id를 path parameter로 지정하여 API 호출 시 id에 해당하는 상품 정보들을 DB에서 조회합니다.

<img width="850" alt="스크린샷 2021-08-05 오후 3 54 25" src="https://user-images.githubusercontent.com/84955774/128305799-a4036650-fda5-4a8c-8963-2615e6ab6601.png">

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-06 01:28 UTC, Kang-kyunghun requested changes

2021-08-06 01:28 UTC, Kang-kyunghun commented on products/views.py
> +class ProductDetailView(View):
```suggestion
class ProductView(View):
```

2021-08-06 01:28 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({"message":"PRODUCT_DOES_NOT_EXIST"}, status=400)
exception 꼼꼼히 잘 잡아주셨습니다 👍  exception으로 에러 핸들링 하는 방법도 좋지만,  `DoesNotExist` 가 발생할 수 있는 로직에서 `if` 조건문으로 먼저 데이터 존재 여부를 따져보는 것이 좋습니다. 

exception처리를 할 경우 코드를 눈으로 읽으면서 천천히 내려오다가 언제 어느 시점에 에러 핸들링을 하는지 알 기가 어렵습니다 (exception이 모두 제일 아래에 있기 때문에 가독성이 떨어진다고 표현할 수 있습니다.)

이러한 이유로 로직상에서 잡을 수 있는 에러는 모두 잡고, 정말 어쩔 수 없는 경우에 exception 처리를 해주는 것이 좋습니다.

또한 if로 처리하는 것이 except로 처리하는 것보다 더 효율적이다고 알려져 있습니다.

2021-08-06 01:28 UTC, Kang-kyunghun commented on products/views.py
> +                image_list.append(image.image_url)
1. image 정보를 product 객체로부터 한 번 가져와 보세요.
2. image을 list로 만드셨는데, list comprehension으로 바꿔보세요.

2021-08-06 05:26 UTC, jssong1592 commented on products/views.py
> +class ProductDetailView(View):
뷰 클래스명을 제안 주신대로 수정하고, url conf에서도 정상적으로 임포트되게 수정하였습니다.

2021-08-06 05:28 UTC, jssong1592 commented on products/views.py
> +            return JsonResponse({"message":"PRODUCT_DOES_NOT_EXIST"}, status=400)
해당 에러 핸들링을 팁 주신 대로 인스턴스 선언 전에 if조건문으로 핸들링할 수 있도록 옮겼습니다!

2021-08-06 05:29 UTC, jssong1592 commented on products/views.py
> +                image_list.append(image.image_url)
1,2번 모두 반영하였습니다!

2021-08-06 05:33 UTC, jssong1592 commented
코드 수정 후 정상적으로 응답하는 것을 확인했습니다.

<img width="845" alt="스크린샷 2021-08-06 오후 2 31 38" src="https://user-images.githubusercontent.com/84955774/128460995-76c20912-8f3c-49ab-8b82-e99eec241fcc.png">
<img width="848" alt="스크린샷 2021-08-06 오후 2 31 56" src="https://user-images.githubusercontent.com/84955774/128461009-ab6b4861-f79e-4bc5-af73-a0e8ab1236d3.png">

2021-08-08 03:49 UTC, Kang-kyunghun requested changes

2021-08-08 03:49 UTC, Kang-kyunghun commented on products/views.py
> +        }
```suggestion
        product = Product.objects.get(id=product_id)
        
        response = {
            "id"               : product.id,
            "name"             : product.name,
            "price"            : int(product.price),
            "style_code"       : product.style_code,
            "origin"           : product.origin,
            "manufacture_date" : product.manufacture_date,
            "description"      : product.description,
            "image_url"        : product.image_url,
            "image_list"       :  [image.image_url for image in product.detailimage_set.all()],
            "color"            : product.color.name,
            "sub_category"     : product.sub_category.sub_category,
            "category"         : product.sub_category.category.category,
        }
```
product로부터 이미지 정보 가져오는 방법 잘 적용하셨습니다.!!!
image_list 변수가 1번만 사용되고, 해당 내용은 reponse에 있는 것이 더 가독성에 좋을 것 같습니다.
해당 내용만 수정하면 merge 하겠습니다.

2021-08-09 01:34 UTC, jssong1592 commented on products/views.py
> +        }
image_list 리스트 내포 식을 response 내부로 옮겼습니다! 또, 프론트와 상의하여 이중 Dict가 아니라 response를 그대로 응답하게끔 JsonResponse를 수정하였습니다.
<img width="851" alt="스크린샷 2021-08-09 오전 10 31 24" src="https://user-images.githubusercontent.com/84955774/128652548-0f3a21ea-639a-4fca-bd15-10b8ff1a196b.png">

2021-08-09 01:57 UTC, Kang-kyunghun commented
LGTM~~~!!!

2021-08-09 01:57 UTC, merged