APP: users 회원가입/로그인 구현
wecode-bootcamp-korea/23-1st-Gaebalance-backend pull request #5
Opened 2021-08-05 09:19 UTC by damdream

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!
<img width="548" alt="스크린샷 2021-08-05 오후 5 43 53" src="https://user-images.githubusercontent.com/81546305/128325756-31e77314-6866-44b7-8ed7-87087d475502.png">
<img width="575" alt="스크린샷 2021-08-05 오후 5 47 30" src="https://user-images.githubusercontent.com/81546305/128325765-6d0c1f11-4ff5-42d2-b949-4537001e742d.png">

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- user app 회원가입, 로그인 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- email, password를 통한 로그인을 진행합니다.
- email, password 정규식을 사용했습니다.
- color는 다중 선택이 가능합니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x]필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-08-06 01:24 UTC, Kang-kyunghun requested changes

2021-08-06 01:24 UTC, Kang-kyunghun commented on users/views.py
> +				return JsonResponse ({"MESSAGE":"INVALID_PASSWORD"},status = 401)
'사용자가 존재하지 않을 때' 와 '존재는 하지만 비밀번호는 틀렸을 때'를 구분하여 에러메세지를 전달하면, 보안에 취약할 수 있습니다. 제3자가 이메일을 알아내어, 비밀번호만 계속 바꿔가며 해킹을 시도할 때에 힌트를 주는 격이 됩니다 🙂  따라서, 보다 안전한 서비스를 만들기 위하여 두 경우의 에러메세지와 에러 코드를 통일시키는 것을 추천드립니다.

2021-08-06 01:24 UTC, Kang-kyunghun commented on users/views.py
> +			    )
bulk create에 대해서 한 번 조사해 보시고 적용해 보시면 좋을 것 같습니다.

2021-08-07 06:00 UTC, damdream commented on users/views.py
> +				return JsonResponse ({"MESSAGE":"INVALID_PASSWORD"},status = 401)
수정하였습니다!

2021-08-07 06:00 UTC, damdream commented on users/views.py
> +			    )
적용완료했습니다~

2021-08-08 03:45 UTC, Kang-kyunghun requested changes

2021-08-08 03:45 UTC, Kang-kyunghun commented on users/views.py
> +class LoginView(View):
로그인 뷰 잘 작성해 주셨습니다~~~!!

2021-08-08 03:45 UTC, Kang-kyunghun commented on users/views.py
> +            UserColor.objects.bulk_create([ UserColor(user=User.objects.get(id=user.id), color=Color.objects.get(id=color_id)) for color_id in data["colors_id"]])
bulk_create 성공 하셨군요!! 잘 하셨어요~!!
1가지만 더 알려드리면 우리는 이미 user을 생성하고 user라는 변수에 생성된 유저를 담았잖아요. 따라서 아래와 같이도 사용할 수 있습니다.
```suggestion
            UserColor.objects.bulk_create([ UserColor(user=user, color=Color.objects.get(id=color_id)) for color_id in data["colors_id"]])
```

2021-08-08 03:45 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse ({"MESSAGE":"INVALID_FORMAT"}, status = 400)
코드의 순서를 조금 바꾸면 좋을 것 같아요. 비밀번호 암호화를 하기 전에 front에서 받아오는 값들을 확인하는 코드가 먼저 있으면 좋을 것 같습니다.
1. 이메일이나, 비밀번호 양식 확인
2. 데이터베이스에 중복값 유무 확인
3. 비밀번호 암호화

순서로 진행 되면 좋을 것 같아요. 프론트에 준 비밀번호가 형식에 맞지 않았는데, 암호화를 하면 안 해도 되는 암호화를 하게 되기 때문입니다.

2021-08-09 09:42 UTC, Kang-kyunghun commented
고생 많으셨습니다~~!!

2021-08-09 09:42 UTC, merged