Add: 장바구니POST API
wecode-bootcamp-korea/23-1st-Gaebalance-backend pull request #8
Opened 2021-08-07 05:49 UTC by byoungjupark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- carts POST API 작성 (로그인 데코레이터 구현 가정 하에 작성함)
		 
## 수정 사항들 자세한 내용
- carts urls.py 생성 및 url 작성
- DB에 존재하지 않는 객체인 경우 에러 처리
- request value가 빈 값인 경우 에러 처리
- 장바구니 상품 수량이 0개인 경우 에러 처리
- 동일 상품과 사이즈에 대한 POST 요청 시, Cart 객체 수량 업데이트
- 새로운 상품인 경우, Cart 객체 생성

## 기타 질문 및 특이 사항
- 처음에는 update_or_create 메소드로 구현하려 하였으나, 객체 create와 update일 때 count 필드 작성법이 달랐습니다.
결국 Cart 객체의 DB 존재여부에 따른 조건문이 장황하게 되었는데, 간결하게 작성하는 쪽으로 고민하고 있습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

<img width="334" alt="스크린샷 2021-08-07 오후 2 43 25" src="https://user-images.githubusercontent.com/63541271/128589639-60200269-6782-4736-a593-bec280a60bf6.png">

2021-08-08 04:02 UTC, Kang-kyunghun requested changes

2021-08-08 04:02 UTC, Kang-kyunghun commented on carts/views.py
> +                 return JsonResponse({"message":"VALUE_ERROR"}, status = 400)
해당 코드는 위의 product나 size를 확인 하는 과정에서 같이 판단 되기 때문에 없어도 괜찮을 것 같네요.

2021-08-08 04:02 UTC, Kang-kyunghun commented on carts/views.py
> +                return JsonResponse({"message":"CREATED"}, status = 201)
이 부분이 update_or_create를 사용하려다가 count 부분 때문에 바뀐 부부인거죠?
update_or_create 대신에 get_or_create을 사용한 뒤에 count에 대한 부분만 따로 update하면 어떨까요?
한 번 고민의 시간을 가져보시고 저랑 만나서 이야기 해봐요.

2021-08-09 08:35 UTC, byoungjupark commented on carts/views.py
> +                 return JsonResponse({"message":"VALUE_ERROR"}, status = 400)
네 이해했고 위 코드 삭제했습니다!

2021-08-09 08:40 UTC, byoungjupark commented on carts/views.py
> +                return JsonResponse({"message":"CREATED"}, status = 201)
경훈님! Cart 객체의 count 필드 옵션(default=0)을 추가하는 것이 아닌, 새로운 객체일 경우의 조건문을 추가하여 count 필드에 0을 대입시켜 작성해보았습니다. 해당 코드로도 똑같이 작용된다고 생각되어 마이그레이션 부분을 생략하고 진행해보았습니다. 어떻게 생각하시나요?

2021-08-10 01:36 UTC, Kang-kyunghun requested changes

2021-08-10 01:36 UTC, Kang-kyunghun commented on carts/views.py
> +            return JsonResponse({"message":"CREATED"}, status = 201)
```suggestion
            return JsonResponse({"message":"SUCCESS"}, status = 200)
```
장바구니가 생성되거나 추가되거나 하는 상황이 모두 있으므로 200으로 통일해도 좋을 것 같습니다.

2021-08-10 01:36 UTC, Kang-kyunghun commented on carts/views.py
> +            user     = User.objects.get(id = 5)
user 부분이 하드코딩 되어 있네요. 수정해 주세요.

2021-08-10 01:36 UTC, Kang-kyunghun commented on carts/views.py
> +    @login_deco
```suggestion
    @login_decorator
```
이거는 제가 놓친 부분인데, 데코레이터 이름도 같이 수정 부탁드리겠습니다.

2021-08-10 01:36 UTC, Kang-kyunghun commented on carts/views.py
> +            size     = Size.objects.get(id = data["size_id"])
따로 get하지 않고, 프론트에서 받은 데이터를 get_or_create에 바로 적용해 보세요

2021-08-10 02:28 UTC, byoungjupark commented on carts/views.py
> +            return JsonResponse({"message":"CREATED"}, status = 201)
200으로 통일했습니다

2021-08-10 02:28 UTC, byoungjupark commented on carts/views.py
> +            user     = User.objects.get(id = 5)
수정했습니다

2021-08-10 02:30 UTC, byoungjupark commented on carts/views.py
> +    @login_deco
users.utils 파일 데코레이터 참조해서 login_deco 로 수정했습니다.

2021-08-10 02:30 UTC, byoungjupark commented on carts/views.py
> +            size     = Size.objects.get(id = data["size_id"])
request 데이터 바로 적용했습니다

2021-08-10 04:24 UTC, Kang-kyunghun commented
고생하셨습니다~~ LGTM~~!

2021-08-10 04:24 UTC, merged