Add: 장바구니GET API
wecode-bootcamp-korea/23-1st-Gaebalance-backend pull request #9
Opened 2021-08-07 05:59 UTC by byoungjupark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- carts GET API 작성 (로그인 데코레이터 구현 가정 하에 작성함)
		 
## 수정 사항들 자세한 내용
- Cart 객체의 유저가 없는 경우 에러 대처
- 장바구니 여러 상품에 대한 응답 처리
- 장바구니 총합계 응답에 추가

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

<img width="470" alt="스크린샷 2021-08-07 오후 2 55 49" src="https://user-images.githubusercontent.com/63541271/128589886-08ff42e6-e2cb-42de-8a4d-71347cc73daa.png">

2021-08-08 03:56 UTC, Kang-kyunghun requested changes

2021-08-08 03:56 UTC, Kang-kyunghun commented on carts/views.py
> +            return JsonResponse({"message":"CART_DOES_NOT_EXIST"}, status = 400)
해당 user가 장바구니에 등록된 상품이 없다면 없는데로 빈 list를 반환해 주면 됩니다. 따라서 해당 코드는 없어도 될 것 같습니다.

2021-08-08 03:56 UTC, Kang-kyunghun commented on carts/views.py
> +        response.append({"total_price" : total_price})
1. list을 만드는 과정을 list comprehension으로 바꿔보세요.
2. total price 부분은 aggregate을 사용해 보세요.

2021-08-09 01:59 UTC, byoungjupark commented on carts/views.py
> +        response.append({"total_price" : total_price})
2번에 대해 의문입니다. price는 Product의 필드이기 때문에 Cart 객체에서 aggregate 메소드를 사용할 경우 FieldError가 발생합니다.
이 부분도 장바구니 POST 관  get_or_create 메소드와 함께 얘기해보고자 합니다

2021-08-09 09:24 UTC, byoungjupark commented on carts/views.py
> +        response.append({"total_price" : total_price})
1,2번 말씀하신대로 수정하였습니다.

2021-08-09 09:24 UTC, byoungjupark commented on carts/views.py
> +            return JsonResponse({"message":"CART_DOES_NOT_EXIST"}, status = 400)
위 코드 삭제하였습니다

2021-08-10 01:53 UTC, Kang-kyunghun requested changes

2021-08-10 01:53 UTC, Kang-kyunghun commented on carts/views.py
> +from django.db.models import Sum, F
import 기준으로 정렬해 주세요.

2021-08-10 01:53 UTC, Kang-kyunghun commented on carts/views.py
> +from users.utils import login_deco
이 부분도 import 기준으로 정렬해 주세요.

2021-08-10 01:53 UTC, Kang-kyunghun commented on carts/views.py
> +            for cart in carts]
```suggestion
        response = [{
            "cart_id" : cart.id,
            "name"    : cart.product.name,
            "image"   : cart.product.image_url,
            "color"   : cart.product.color.name,
            "size"    : cart.size.name,
            "count"   : cart.count,
            "price"   : int(cart.count * cart.product.price)
        } for cart in carts]
```
list comprehension 잘 적용하셨습니다. 
구조만 다음과 같이 수정하면 가독성이 더 올라 갈 것 같습니다.

2021-08-10 01:53 UTC, Kang-kyunghun commented on carts/views.py
> +        return JsonResponse({"response":response}, status = 200)
응답의 구조가 조금 부자연스럽습니다. 총액이 다시 dictionary에 들어갈 필요는 없을 것 같습니다.
아래와 같은 구조로 응답이 나오게 수정해 보세요.
```suggestion
{
    carts = [{},{},...,{}],
    total_price = 10000
}
      
```

2021-08-10 03:43 UTC, byoungjupark commented on carts/views.py
> +from django.db.models import Sum, F
재정렬했습니다

2021-08-10 03:43 UTC, byoungjupark commented on carts/views.py
> +from users.utils import login_deco
재정렬했습니다

2021-08-10 03:44 UTC, byoungjupark commented on carts/views.py
> +        return JsonResponse({"response":response}, status = 200)
위 리뷰와 함께 total_price 부분 딕셔너리 형태로 추가하였습니다!

2021-08-10 04:27 UTC, Kang-kyunghun requested changes

2021-08-10 04:27 UTC, Kang-kyunghun commented on carts/views.py
> +        } for cart in carts],
```suggestion
            "cart" : [{
                "cart_id" : cart.id,
                "name"    : cart.product.name,
                "image"   : cart.product.image_url,
                "color"   : cart.product.color.name,
                "size"    : cart.size.name,
                "count"   : cart.count,
                "price"   : int(cart.count * cart.product.price)
            } for cart in carts],
```
cart라는 key 있는 list 데이터들이 cart랑 같은 레벨에 있는 것처럼 보이지 않게 다음과 같이 수정하면 좋을 것 같아요.

2021-08-10 04:27 UTC, Kang-kyunghun commented on carts/views.py
> +        return JsonResponse({"response":response}, status = 200)
굳~~~~~!!!

2021-08-10 04:59 UTC, byoungjupark commented on carts/views.py
> +        } for cart in carts],
cart 안의 데이터들 안쪽으로 들여쓰기하였습니다.

2021-08-10 10:30 UTC, Kang-kyunghun commented
LGTM~~!!

2021-08-10 10:30 UTC, merged